### ISSUE TITLE
Chapter 4: Wilson_score_CI_2x2 function missing?

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/contingencytables#16]
Hi Morten,

While finishing issue #4 (translating Chapter 4 functions), I noticed that the files on http://folk.uio.no/mortenfa/SACT/R/chap4R.zip contain the file Wilson_score_CI_1x2.R, which is also present on [the chapter 2 files](http://folk.uio.no/mortenfa/SACT/R/chap2R.zip). 

Considering that:

- all Chap. 4 functions are about 2x2 tables,
- the MATLAB equivalent files (http://folk.uio.no/mortenfa/SACT/Matlab/chap4M.zip) contain Wald_CI_CC_2x2.m, and
- the code inside `chap4R.zip/Wilson_score_CI_1x2.R` is functionally identical to the one in `chap2R.zip/Wilson_score_CI_1x2.R`,

I am seeking confirmation that the R script on chap4R.zip is the wrong one.

If this is indeed the case and the R code for the 2x2 function isn't there, I could translate `chap4M.zip/Wilson_score_CI_CC_2x2.m` from MATLAB into R, though it would be great to have a few examples (perhaps from the SACT book) so I can make sure the output is correct.

Best,
Waldir

**Comment by mortenfagerland** [comment]
Hi Waldir,


The Wilson_score_CI_1x2 file in chapter 4 is identical to the one in chapter 2. It's there because one or more of the other files in chapter 4 call this function, so it has been copied to chapter 4 to avoid problems for people who only download the chapter 4 files. This will be no problem when everything is packaged together. Just make sure that the files in chapter 4 that need to call the Wilson_score_CI_1x2 function are able to do this :-)


Please let me know if I have explained this badly ;-)


Thanks again for doing this!


Morten


________________________________
From: Waldir Leoncio ***@***.***>
Sent: 13 April 2021 08:49
To: ocbe-uio/contingencytables
Cc: Morten Fagerland; Assign
Subject: [ocbe-uio/contingencytables] Chapter 4: Wilson_score_CI_2x2 function missing? (#16)


Hi Morten,

While finishing issue #4<https://github.com/ocbe-uio/contingencytables/issues/4> (translating Chapter 4 functions), I noticed that the files on http://folk.uio.no/mortenfa/SACT/R/chap4R.zip contain the file Wilson_score_CI_1x2.R, which is also present on the chapter 2 files<http://folk.uio.no/mortenfa/SACT/R/chap2R.zip>.

Considering that:

  *   all Chap. 4 functions are about 2x2 tables,
  *   the MATLAB equivalent files (http://folk.uio.no/mortenfa/SACT/Matlab/chap4M.zip) contain Wald_CI_CC_2x2.m, and
  *   the code inside chap4R.zip/Wilson_score_CI_1x2.R is functionally identical to the one in chap2R.zip/Wilson_score_CI_1x2.R,

I am seeking confirmation that the R script on chap4R.zip is the wrong one.

If this is indeed the case and the R code for the 2x2 function isn't there, I could translate chap4M.zip/Wilson_score_CI_CC_2x2.m from MATLAB into R, though it would be great to have a few examples (perhaps from the SACT book) so I can make sure the output is correct.

Best,
Waldir

-

**Comment by wleoncio** [comment]
Got it, thanks!

ti., 13.04.2021 kl. 03.29 -0700, skrev mortenfagerland:

Hi Waldir,


The Wilson_score_CI_1x2 file in chapter 4 is identical to the one in chapter 2. It's there because one or more of the other files in chapter 4 call this function, so it has been copied to chapter 4 to avoid problems for people who only download the chapter 4 files. This will be no problem when everything is packaged together. Just make sure that the files in chapter 4 that need to call the Wilson_score_CI_1x2 function are able to do this :-)


Please let me know if I have explained this badly ;-)


Thanks again for doing this!


Morten


________________________________
From: Waldir Leoncio ***@***.***>
Sent: 13 April 2021 08:49
To: ocbe-uio/contingencytables
Cc: Morten Fagerland; Assign
Subject: [ocbe-uio/contingencytables] Chapter 4: Wilson_score_CI_2x2 function missing? (#16)


Hi Morten,

While finishing issue #4<https://github.com/ocbe-uio/contingencytables/issues/4> (translating Chapter 4 functions), I noticed that the files on http://folk.uio.no/mortenfa/SACT/R/chap4R.zip contain the file Wilson_score_CI_1x2.R, which is also present on the chapter 2 files<http://folk.uio.no/mortenfa/SACT/R/chap2R.zip>.

Considering that:

* all Chap. 4 functions are about 2x2 tables,
* the MATLAB equivalent files (http://folk.uio.no/mortenfa/SACT/Matlab/chap4M.zip) contain Wald_CI_CC_2x2.m, and
* the code inside chap4R.zip/Wilson_score_CI_1x2.R is functionally identical to the one in chap2R.zip/Wilson_score_CI_1x2.R,

I am seeking confirmation that the R script on chap4R.zip is the wrong one.

If this is indeed the case and the R code for the 2x2 function isn't there, I could translate chap4M.zip/Wilson_score_CI_CC_2x2.m from MATLAB into R, though it would be great to have a few examples (perhaps from the SACT book) so I can make sure the output is correct.

Best,
Waldir

-

**Comment by wleoncio** [comment]
Adding task to close this issue when completed:

- [x] Add unit tests to Ch4 functions specifically calling `Wilson_score_CI_1x2()`

**Comment by wleoncio** [comment]
Resolved by the commits mentioned above + a3dad3594d5922af566840f4899652d3a4f75121.
